routes/web.php
<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\MessageController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WomanController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Test git push for login

Route::get('/', function () {
    return view('login');
});

Route::get('login', [AuthController::class, 'loginWithGoogle'])->name('login');
Route::prefix('google')->name('google.')->group(function () {
    Route::get('login', [AuthController::class, 'loginWithGoogle'])->name('login');
    Route::any('callback', [AuthController::class, 'callbackFromGoogle'])->name('callback');
});
Route::middleware('auth')->group(function () {
    Route::get('top-list', [UserController::class, 'getTopList'])->name('top-list');
    Route::get('lady/{id}', [WomanController::class, 'getProfile'])->name('profile');
    Route::post('send-message', [MessageController::class, 'sendMessage'])->name('send-message');
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Message extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'user_id',
        'woman_id',
        'content'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function woman()
    {
        return $this->belongsTo(Woman::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'avatar',
        'google_id',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function messages()
    {
        return $this->hasMany(Message::class);
    }
}

app/Models/Woman.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Woman extends Model
{
    use HasFactory, SoftDeletes;

    public function messages()
    {
        return $this->hasMany(Message::class);
    }
}

app/Http/Controllers/AuthController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Laravel\Socialite\Facades\Socialite;

class AuthController extends Controller
{
    public function loginWithGoogle()
    {
        return Socialite::driver('google')->redirect();
    }

    public function callbackFromGoogle()
    {
        try {
            $user = Socialite::driver('google')->stateless()->user();

            $is_user = User::where('email', $user->getEmail())->first();
            if (!$is_user) {
                $saveUser = User::updateOrCreate([
                    'google_id' => $user->getId(),
                ], [
                    'name' => $user->getName(),
                    'email' => $user->getEmail(),
                    'avatar' => $user->getAvatar(),
                    'password' => Hash::make($user->getName() . '@' . $user->getId())
                ]);
            } else {
                $saveUser = User::where('email',  $user->getEmail())->update([
                    'google_id' => $user->getId(),
                ]);
                $saveUser = User::where('email', $user->getEmail())->first();
            }
            Auth::loginUsingId($saveUser->id);
            return redirect()->route('top-list');
        } catch (\Throwable $th) {
            throw $th;
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MessageRequest;
use App\Models\Message;

class MessageController extends Controller
{
    public function sendMessage(MessageRequest $request)
    {
        $data = $request->validated();
        $data['user_id'] = auth()->id();
        $message = Message::where([
            ['user_id', $data['user_id']],
            ['woman_id', $data['woman_id']]
        ])->exists();
        if ($message) {
            return view('toast', ['error' => 'Bạn đã gửi lời chúc đến người này ròi!!']);
        }
        $message = Message::create($data);
        return view('toast', ['success' => 'Gửi lời chúc thành công!!']);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    public function getTopList()
    {
        return view('welcome');
    }
}

app/Http/Controllers/WomanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Woman;
use Illuminate\Http\Request;

class WomanController extends Controller
{
    public function getProfile($id)
    {
        $profile = Woman::where('id', $id)->with('messages')->firstOrFail();
        $profile = Woman::where('id', $id)->with("messages", function ($messages) {
            $messages->with("user");
        })->firstOrFail();
        return view('profile', compact('profile'));
    }
}

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6 text-center">
            <a href="{{ route('google.login') }}" class="btn btn-danger btn-lg btn-block">
                <i class="fab fa-google mr-2"></i> Login with Google
            </a>
        </div>
    </div>
</div>
<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- Font Awesome JS -->
<script src="https://kit.fontawesome.com/1b4618bf6b.js" crossorigin="anonymous"></script>
</body>
</html>

resources/views/profile.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ asset('assets/css/profile.css') }}">
    <style>
        @media (max-width: 740px) {
            .page-container {
                background-image: linear-gradient(0, rgba(233, 147, 168, 0.5), rgba(251, 126, 182, 0.5)), url({{ $profile->image }});
                background-repeat: no-repeat;
                background-size: cover;
                background-position: center;
                height: 100vh;
                margin: 0 auto;
            }
        }
    </style>
</head>

<body>
    <div class="page-container">
        <div class="display-message top-0 start-50 translate-middle-x position-fixed mt-2"></div>
        <div class="d-flex justify-content-between">
            <button class="btn">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
                    class="bi bi-arrow-left">
                    <path fill-rule="evenodd"
                        d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z" />
                </svg>
            </button>
        </div>
        <div class="content">
            <div class="top-header d-flex justify-content-center mt-2">
                <h1>{{ $profile->name }}</h1>
            </div>
            <div class="image">
                <img src="{{ $profile->image }}" class="rounded-circle mx-auto d-block" alt="...">
            </div>
            <div class="messages-list py-3">
                <div class="overflow-auto scrollbar">
                    @foreach ($profile->messages as $message)
                        <div class="force-overflow">
                            <div class="card m-2 shadow-sm">
                                <div class="card-body">
                                    <b class="card-subtitle mb-2 text-muted border-bottom">{{ $message->user->email }}
                                    </b>
                                    <p class="card-text">
                                        {{ $message->content }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
        <div class="px-4 py-2 message-input">
            <div class="input-group d-flex mx-1 justify-content-between">
                <input type="text" class="form-control message rounded" id="message"
                    placeholder="Gửi lời chúc đến {{ $profile->name }}">
                <button class="btn rounded-circle btn-send-messsage" style="color:rgb(255, 255, 255)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                        class="bi bi-send-fill" viewBox="0 0 20 20">
                        <path
                            d="M15.964.686a.5.5 0 0 0-.65-.65L.767 5.855H.766l-.452.18a.5.5 0 0 0-.082.887l.41.26.001.002 4.995 3.178 3.178 4.995.002.002.26.41a.5.5 0 0 0 .886-.083l6-15Zm-1.833 1.89L6.637 10.07l-.215-.338a.5.5 0 0 0-.154-.154l-.338-.215 7.494-7.494 1.178-.471-.47 1.178Z" />
                    </svg>
                </button>
            </div>
        </div>
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous">
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script>
    function sendMessage() {
        $.ajax({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            type: "POST",
            url: "{{ route('send-message') }}",
            data: {
                woman_id: {{ $profile->id }},
                content: $('.message').val(),
            },
            success: function(data) {
                $(".display-message").html(data, 1000);
            },
            error: function(XMLHttpRequest, textStatus, errorThrown) {
                alert(errorThrown);
            }
        });
    }

    function checkEmptyMessage() {

    }
    $(document).ready(function() {
        $('body').delegate('.btn-send-messsage', 'click', function(e) {
            if (confirm("Bạn chỉ có thể gửi 1 lời nhắn cho 1 người!!") == true) {
                sendMessage()
            }
        })
    });
</script>

</html>

resources/views/toast.blade.php
@if (isset($error))
    <div class="toast align-items-center text-bg-danger border-0 show" role="alert" aria-live="assertive"
        aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                {{ $error }}
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Close"></button>
        </div>
    </div>
@elseif (isset($success))
    <div class="toast align-items-center text-bg-success border-0 show" role="alert" aria-live="assertive"
        aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body">
                {{ $success }}
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                aria-label="Close"></button>
        </div>
    </div>
@endif